FROM node:24-alpine AS dependencies
WORKDIR /app
COPY package.json package-lock.json ./
COPY apps/backend/package.json ./apps/backend/package.json
COPY apps/frontend/package.json ./apps/frontend/package.json
COPY apps/generator/package.json ./apps/generator/package.json
RUN npm ci

FROM dependencies AS build
ARG APP
COPY tsconfig.base.json ./
COPY apps/${APP} ./apps/${APP}
RUN npm run build --workspace=apps/${APP}
RUN npm prune --omit=dev

FROM node:24-alpine AS runtime
ARG APP
ENV NODE_ENV=production
WORKDIR /app
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/apps/${APP}/dist ./dist
COPY apps/backend/migrations ./migrations
USER node
CMD ["node", "dist/server.js"]
